export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const CUSTOMERS_REPOSITORY = 'CUSTOMERS_REPOSITORY';
export const INTERACTIONS_REPOSITORY = 'INTERACTIONS_REPOSITORY';
export const DEALS_REPOSITORY = 'DEALS_REPOSITORY';
